name: hackernews-daily-top

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup FFmpeg
      uses: federicocarboni/setup-ffmpeg@v3.1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Run Main
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MODEL: ${{ vars.MODEL }}
        ENDPOINT: ${{ vars.ENDPOINT }}
        XI_API_KEY: ${{ secrets.XI_API_KEY }}
        APP_ID: ${{ vars.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: go run main.go
