name: hackernews-daily-top

on:
  schedule:
    - cron: "0 17 * * *"  # 北京时间次日凌晨1:00 (UTC+8)
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup FFmpeg
      uses: federicocarboni/setup-ffmpeg@v3.1

    # https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?pivots=programming-language-go&tabs=windows%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi
    - name: Install Microsoft Speech SDK
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential ca-certificates libasound2-dev libssl-dev wget
        export SPEECHSDK_ROOT="$HOME/speechsdk"
        mkdir -p "$SPEECHSDK_ROOT"
        wget -O SpeechSDK-Linux.tar.gz https://aka.ms/csspeech/linuxbinary
        tar --strip 1 -xzf SpeechSDK-Linux.tar.gz -C "$SPEECHSDK_ROOT"
        ls -l "$SPEECHSDK_ROOT"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Run Main
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MODEL: ${{ vars.MODEL }}
        ENDPOINT: ${{ vars.ENDPOINT }}
        XI_API_KEY: ${{ secrets.XI_API_KEY }}
        APP_ID: ${{ vars.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        SPEECH_REGION: ${{ vars.SPEECH_REGION }}
        SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
      run: |
        export SPEECHSDK_ROOT="$HOME/speechsdk"
        export CGO_CFLAGS="-I$SPEECHSDK_ROOT/include/c_api"
        export CGO_LDFLAGS="-L$SPEECHSDK_ROOT/lib/x64 -lMicrosoft.CognitiveServices.Speech.core"
        export LD_LIBRARY_PATH="$SPEECHSDK_ROOT/lib/x64:$LD_LIBRARY_PATH"
        go run main.go
